export const ADD_TO_BAG_REQUEST = "ADD_TO_BAG_REQUEST";
export const ADD_TO_BAG_SUCCESS = "ADD_TO_BAG_SUCCESS";
export const ADD_TO_BAG_FAILURE = "ADD_TO_BAG_FAILURE";

export const GET_BAG_ITEMS_REQUEST = "GET_BAG_ITEMS_REQUEST";
export const GET_BAG_ITEMS_SUCCESS = "GET_BAG_ITEMS_SUCCESS";
export const GET_BAG_ITEMS_FAILURE = "GET_BAG_ITEMS_FAILURE";

export const REMOVE_BAG_ITEMS_REQUEST = "REMOVE_BAG_ITEMS_REQUEST";
export const REMOVE_BAG_ITEMS_SUCCESS = "REMOVE_BAG_ITEMS_SUCCESS";
export const REMOVE_BAG_ITEMS_FAILURE = "REMOVE_BAG_ITEMS_FAILURE";
