export const GET_ALL_WATCHES_REQUEST = "GET_ALL_WATCHES_REQUEST";
export const GET_ALL_WATCHES_SUCCESS = "GET_ALL_WATCHES_SUCCESS";
export const GET_ALL_WATCHES_FAILURE = "GET_ALL_WATCHES_FAILURE";

export const GET_WATCHES_SUCCESS = "GET_WATCHES_SUCCESS";
